### ISSUE TITLE
logback reloadDefaultConfiguration() and logback-logQuery

### ISSUE THREAD

**Issue by mjj1409** [pavax/hawtio-logback#2]
First off, thanks for putting this together, our project is also using logback and I'm now able to see our logs appear in hawtio's 'Logs' tab. We are using the Java Config example you provided in our Spring App and it worked right away, awesome stuff!  
I'm running into an issue you may have also come across, I'm not sure if its specific to this implementation or not.  Basically, we have enabled the ability to set the log levels via hawtio by adding the <jmxConfigurator/> element to our logback.xml file. This works fine, changing log levels updates what logs are sent to the 'Logs' tab; however, when I run reloadDefaultConfiguration(), the log levels are reset to what is defined in logback.xml, but log output ceases to show on the 'Logs' tab.   Its seems as if reloadDefaultConfiguration() erases the registration of the LogQuery @Bean.

**Comment by mjj1409** [comment]
I was able to get this to work by extending the LogbackLogQuery like so

public class ReloadableLogbackLogQuery extends LogbackLogQuery implements
		LoggerContextListener {

	public ReloadableLogbackLogQuery(
			LogQueryAwareAppender logQueryAwareAppender,
			LoggerContext loggerContext) {
		super(logQueryAwareAppender);
		loggerContext.addListener(this);
	}

	/**
	 * this listener should not be removed when the LoggerContext is reloaded
	 */
	@Override
	public boolean isResetResistant() {
		return true;
	}

	/**
	 * when LoggerContext is reloaded start the LogbackLogQuery back up.
	 */
	@Override
	public void onReset(LoggerContext loggerContext) {
		super.start();
	}

	@Override
	public void onLevelChange(Logger logger, Level level) {/* noop */
	}

	@Override
	public void onStart(LoggerContext loggerContext) {/* noop */
	}

	@Override
	public void onStop(LoggerContext loggerContext) {/* noop */
	}

}

**Comment by pavax** [comment]
Thank you very much for this bug-report and the provided fix. I created a pull-request. If you wan't check it out you and let me know if works for you.

**Comment by mjj1409** [comment]
Thanks for the fix, works perfectly!
